"""
TIMELINE REPORT GENERATOR
Legal-Grade Appearance Timeline Reports with Comprehensive Analysis
"""

import json
from typing import List, Dict, Any
from datetime import datetime
import pandas as pd
from pathlib import Path

class TimelineReportGenerator:
    """
    Generates comprehensive timeline reports for legal and investigative use
    """
    
    def __init__(self):
        self.report_templates = {
            'no_detection': self._generate_no_detection_report,
            'single_footage': self._generate_single_footage_report,
            'multiple_footage': self._generate_multiple_footage_report,
            'comprehensive': self._generate_comprehensive_report
        }
    
    def generate_report(self, analysis_results: List[Dict], case_info: Dict) -> Dict:
        """
        Generate comprehensive timeline report based on analysis results
        """
        try:
            # Determine report type
            detection_count = sum(1 for result in analysis_results if result.get('status') == 'detection_found')
            
            if detection_count == 0:
                return self._generate_no_detection_report(analysis_results, case_info)
            elif len(analysis_results) == 1:
                return self._generate_single_footage_report(analysis_results[0], case_info)
            else:
                return self._generate_multiple_footage_report(analysis_results, case_info)
                
        except Exception as e:
            return {
                'error': f'Report generation failed: {str(e)}',
                'timestamp': datetime.now().isoformat()
            }
    
    def _generate_no_detection_report(self, analysis_results: List[Dict], case_info: Dict) -> Dict:
        """Generate report when no detections found"""
        footage_count = len(analysis_results)
        footage_files = [result.get('footage_file', 'Unknown') for result in analysis_results]
        
        return {
            'report_type': 'no_detection',
            'case_info': case_info,
            'summary': {
                'detection_status': 'NOT DETECTED',
                'footage_files_analyzed': footage_count,
                'total_analysis_time': sum(
                    float(r.get('analysis_duration', 0)) for r in analysis_results
                ),
                'message': f'This person was NOT detected in any of the {footage_count} submitted CCTV footage files.'
            },
            'footage_analysis': [
                {
                    'footage_file': result.get('footage_file', 'Unknown'),
                    'status': 'NO DETECTION',
                    'duration_analyzed': f"{result.get('analysis_duration', 0):.1f}s",
                    'frames_analyzed': result.get('frames_analyzed', 0)
                }
                for result in analysis_results
            ],
            'technical_details': {
                'analysis_method': '5-Method Multi-Modal Ensemble',
                'confidence_thresholds': {
                    'high': '85%+',
                    'medium': '65-84%',
                    'low': '45-64%'
                },
                'detection_algorithms': [
                    'Face Recognition (Primary)',
                    'Body Structure Analysis',
                    'Motion Pattern Recognition',
                    'Person Tracking',
                    'Crowd Analysis'
                ]
            },
            'generated_at': datetime.now().isoformat(),
            'legal_notice': 'This report is generated by AI analysis and should be used as investigative guidance only.'
        }
    
    def _generate_single_footage_report(self, analysis_result: Dict, case_info: Dict) -> Dict:
        """Generate report for single footage analysis"""
        timeline_report = analysis_result.get('timeline_report', {})
        timeline_entries = timeline_report.get('timeline_entries', [])
        
        # Create formatted table data
        table_data = []
        for entry in timeline_entries:
            table_data.append({
                'Footage File': entry['footage_file'],
                'Location': entry['location'],
                'Appearance': entry['appearance'],
                'Start Time': entry['start_time'],
                'End Time': entry['end_time'],
                'Total Duration': entry['total_duration'],
                'Avg. Confidence': entry['avg_confidence']
            })
        
        return {
            'report_type': 'single_footage_detection',
            'case_info': case_info,
            'summary': {
                'detection_status': 'DETECTED',
                'footage_file': timeline_report.get('footage_file', 'Unknown'),
                'location': timeline_report.get('location', 'Unknown'),
                'total_appearances': timeline_report.get('total_appearances', 0),
                'total_detection_time': self._calculate_total_detection_time(timeline_entries)
            },
            'appearance_timeline': table_data,
            'detailed_analysis': {
                'detection_method': timeline_report.get('analysis_metadata', {}).get('detection_method', 'Unknown'),
                'cooldown_period': timeline_report.get('analysis_metadata', {}).get('cooldown_period', 'Unknown'),
                'confidence_distribution': self._analyze_confidence_distribution(timeline_entries),
                'quality_metrics': self._analyze_quality_metrics(timeline_entries)
            },
            'raw_statistics': {
                'total_detections': analysis_result.get('raw_detections_count', 0),
                'coalesced_appearances': analysis_result.get('coalesced_appearances', 0),
                'analysis_summary': analysis_result.get('analysis_summary', {})
            },
            'generated_at': datetime.now().isoformat(),
            'legal_notice': 'This report is generated by AI analysis. All detections should be verified by human investigators.'
        }
    
    def _generate_multiple_footage_report(self, analysis_results: List[Dict], case_info: Dict) -> Dict:
        """Generate comprehensive report for multiple footage analysis"""
        all_timeline_entries = []
        footage_summaries = []
        
        total_appearances = 0
        total_detection_time = 0
        
        for result in analysis_results:
            if result.get('status') == 'detection_found':
                timeline_report = result.get('timeline_report', {})
                timeline_entries = timeline_report.get('timeline_entries', [])
                
                # Add to master timeline
                all_timeline_entries.extend(timeline_entries)
                
                # Create footage summary
                footage_summaries.append({
                    'footage_file': timeline_report.get('footage_file', 'Unknown'),
                    'location': timeline_report.get('location', 'Unknown'),
                    'appearances': len(timeline_entries),
                    'detection_time': self._calculate_total_detection_time(timeline_entries),
                    'max_confidence': max(
                        float(entry['avg_confidence'].replace('%', '')) 
                        for entry in timeline_entries
                    ) if timeline_entries else 0
                })
                
                total_appearances += len(timeline_entries)
                total_detection_time += self._calculate_total_detection_time(timeline_entries, return_seconds=True)
            
            elif result.get('status') == 'no_detection':
                footage_summaries.append({
                    'footage_file': result.get('footage_file', 'Unknown'),
                    'location': 'Unknown',
                    'appearances': 0,
                    'detection_time': '0s',
                    'status': 'NOT DETECTED'
                })
        
        # Sort timeline by start time
        all_timeline_entries.sort(key=lambda x: x['start_time'])
        
        # Create master timeline table
        master_timeline = []
        for entry in all_timeline_entries:
            master_timeline.append({
                'Footage File': entry['footage_file'],
                'Location': entry['location'],
                'Appearance': entry['appearance'],
                'Start Time': entry['start_time'],
                'End Time': entry['end_time'],
                'Total Duration': entry['total_duration'],
                'Avg. Confidence': entry['avg_confidence']
            })
        
        return {
            'report_type': 'multiple_footage_comprehensive',
            'case_info': case_info,
            'executive_summary': {
                'detection_status': 'DETECTED' if total_appearances > 0 else 'NOT DETECTED',
                'total_footage_files': len(analysis_results),
                'files_with_detections': len([r for r in analysis_results if r.get('status') == 'detection_found']),
                'total_appearances': total_appearances,
                'total_detection_time': self._seconds_to_duration(total_detection_time),
                'investigation_timeline': self._create_investigation_timeline(all_timeline_entries)
            },
            'master_appearance_timeline': master_timeline,
            'footage_breakdown': footage_summaries,
            'cross_reference_analysis': {
                'location_correlation': self._analyze_location_correlation(footage_summaries),
                'temporal_analysis': self._analyze_temporal_patterns(all_timeline_entries),
                'confidence_trends': self._analyze_confidence_trends(all_timeline_entries)
            },
            'technical_analysis': {
                'detection_algorithms': [
                    'Face Recognition (Primary)',
                    'Body Structure Analysis', 
                    'Motion Pattern Recognition',
                    'Person Tracking',
                    'Crowd Analysis'
                ],
                'quality_assurance': {
                    'false_positive_prevention': 'High confidence threshold (85%+) for auto-acceptance',
                    'human_review_required': 'Medium confidence (65-84%) flagged for verification',
                    'coalescing_logic': 'Fragmented detections merged using cooldown period'
                }
            },
            'generated_at': datetime.now().isoformat(),
            'legal_disclaimer': 'This AI-generated report provides investigative guidance. All findings should be independently verified by qualified investigators.'
        }
    
    def _calculate_total_detection_time(self, timeline_entries: List[Dict], return_seconds: bool = False) -> str:
        """Calculate total detection time from timeline entries"""
        total_seconds = 0
        
        for entry in timeline_entries:
            duration_str = entry.get('total_duration', '0s')
            seconds = self._duration_to_seconds(duration_str)
            total_seconds += seconds
        
        if return_seconds:
            return total_seconds
        
        return self._seconds_to_duration(total_seconds)
    
    def _duration_to_seconds(self, duration_str: str) -> float:
        """Convert duration string to seconds"""
        try:
            if 'h' in duration_str:
                parts = duration_str.replace('h', '').replace('m', '').replace('s', '').split()
                hours = float(parts[0]) if len(parts) > 0 else 0
                minutes = float(parts[1]) if len(parts) > 1 else 0
                return hours * 3600 + minutes * 60
            elif 'm' in duration_str:
                parts = duration_str.replace('m', '').replace('s', '').split()
                minutes = float(parts[0]) if len(parts) > 0 else 0
                seconds = float(parts[1]) if len(parts) > 1 else 0
                return minutes * 60 + seconds
            else:
                return float(duration_str.replace('s', ''))
        except:
            return 0.0
    
    def _seconds_to_duration(self, seconds: float) -> str:
        """Convert seconds to duration format"""
        if seconds < 60:
            return f"{int(seconds)}s"
        elif seconds < 3600:
            minutes = int(seconds // 60)
            secs = int(seconds % 60)
            return f"{minutes}m {secs}s"
        else:
            hours = int(seconds // 3600)
            minutes = int((seconds % 3600) // 60)
            return f"{hours}h {minutes}m"
    
    def _analyze_confidence_distribution(self, timeline_entries: List[Dict]) -> Dict:
        """Analyze confidence score distribution"""
        confidences = []
        for entry in timeline_entries:
            conf_str = entry.get('avg_confidence', '0%').replace('%', '')
            confidences.append(float(conf_str))
        
        if not confidences:
            return {'min': 0, 'max': 0, 'avg': 0, 'distribution': 'No data'}
        
        return {
            'min_confidence': f"{min(confidences):.1f}%",
            'max_confidence': f"{max(confidences):.1f}%",
            'avg_confidence': f"{sum(confidences)/len(confidences):.1f}%",
            'high_confidence_count': len([c for c in confidences if c >= 85]),
            'medium_confidence_count': len([c for c in confidences if 65 <= c < 85]),
            'distribution_quality': 'Excellent' if min(confidences) >= 85 else 'Good' if min(confidences) >= 65 else 'Requires Review'
        }
    
    def _analyze_quality_metrics(self, timeline_entries: List[Dict]) -> Dict:
        """Analyze detection quality metrics"""
        quality_data = []
        for entry in timeline_entries:
            quality_metrics = entry.get('quality_metrics', {})
            if quality_metrics:
                quality_data.append(quality_metrics)
        
        if not quality_data:
            return {'status': 'No quality data available'}
        
        return {
            'total_detections_analyzed': len(quality_data),
            'quality_assessment': 'Based on occlusion levels, image quality, and detection consistency',
            'recommendation': 'All detections meet minimum quality standards for investigative use'
        }
    
    def _create_investigation_timeline(self, timeline_entries: List[Dict]) -> str:
        """Create a narrative investigation timeline"""
        if not timeline_entries:
            return "No timeline data available"
        
        timeline_entries.sort(key=lambda x: x['start_time'])
        
        if len(timeline_entries) == 1:
            entry = timeline_entries[0]
            return f"Person detected at {entry['location']} from {entry['start_time']} to {entry['end_time']}"
        
        locations = []
        for entry in timeline_entries:
            location = entry['location']
            start_time = entry['start_time']
            if location not in [loc['name'] for loc in locations]:
                locations.append({'name': location, 'first_seen': start_time})
        
        if len(locations) == 1:
            return f"Person tracked at {locations[0]['name']} across {len(timeline_entries)} separate appearances"
        else:
            location_names = [loc['name'] for loc in locations]
            return f"Person movement tracked across {len(locations)} locations: {' → '.join(location_names)}"
    
    def _analyze_location_correlation(self, footage_summaries: List[Dict]) -> Dict:
        """Analyze correlation between locations"""
        locations_with_detections = [
            fs['location'] for fs in footage_summaries 
            if fs.get('appearances', 0) > 0
        ]
        
        return {
            'unique_locations': len(set(locations_with_detections)),
            'location_list': list(set(locations_with_detections)),
            'multi_location_tracking': len(set(locations_with_detections)) > 1
        }
    
    def _analyze_temporal_patterns(self, timeline_entries: List[Dict]) -> Dict:
        """Analyze temporal patterns in detections"""
        if not timeline_entries:
            return {'status': 'No temporal data'}
        
        timeline_entries.sort(key=lambda x: x['start_time'])
        
        return {
            'first_detection': timeline_entries[0]['start_time'],
            'last_detection': timeline_entries[-1]['end_time'],
            'detection_span': f"From {timeline_entries[0]['start_time']} to {timeline_entries[-1]['end_time']}",
            'total_appearances': len(timeline_entries)
        }
    
    def _analyze_confidence_trends(self, timeline_entries: List[Dict]) -> Dict:
        """Analyze confidence trends over time"""
        confidences = []
        for entry in timeline_entries:
            conf_str = entry.get('avg_confidence', '0%').replace('%', '')
            confidences.append(float(conf_str))
        
        if not confidences:
            return {'status': 'No confidence data'}
        
        trend = 'stable'
        if len(confidences) > 1:
            if confidences[-1] > confidences[0] + 5:
                trend = 'improving'
            elif confidences[-1] < confidences[0] - 5:
                trend = 'declining'
        
        return {
            'confidence_trend': trend,
            'consistency': 'high' if max(confidences) - min(confidences) < 10 else 'moderate',
            'reliability_assessment': 'High reliability' if min(confidences) >= 80 else 'Moderate reliability'
        }

# Global report generator
timeline_generator = TimelineReportGenerator()

def generate_comprehensive_timeline_report(analysis_results: List[Dict], case_info: Dict) -> Dict:
    """
    Generate comprehensive timeline report for multiple footage analysis
    """
    return timeline_generator.generate_report(analysis_results, case_info)